// -------------------------------------------------------
// /api/deliverables/cover-letter - Generate cover letter
// Uses AI (via the qrsqpi line-rewrite pattern) to
// generate a tailored cover letter DOCX/RTF
// -------------------------------------------------------

import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { resumeText, targetRole = 'Software Engineer', companyName = 'the company', roleNumber = 1 } = body

    if (!resumeText) {
      return NextResponse.json(
        { error: 'Resume text is required to generate a cover letter' },
        { status: 400 }
      )
    }

    // Generate cover letter content from resume data
    // Extract key experience lines and achievements
    const lines = resumeText.split('\n').filter(l => l.trim())
    const bulletLines = lines.filter(l => /^[•\-\*\u2022]\s/.test(l.trim()) || /^\d+\.\s/.test(l.trim()))
    const nameLine = lines[0]?.trim() || 'Applicant'

    // Build a structured cover letter
    const coverLetter = buildCoverLetter(
      nameLine,
      bulletLines.slice(0, 4),
      targetRole,
      companyName,
      roleNumber
    )

    // Generate RTF document
    const rtf = generateCoverLetterRTF(coverLetter)

    return new NextResponse(rtf, {
      status: 200,
      headers: {
        'Content-Type': 'application/rtf; charset=utf-8',
        'Content-Disposition': `attachment; filename="cover-letter-role-${roleNumber}.doc"`,
      },
    })
  } catch (error: any) {
    console.error('Cover letter deliverable error:', error)
    return NextResponse.json(
      { error: 'Failed to generate cover letter' },
      { status: 500 }
    )
  }
}

function buildCoverLetter(
  name: string,
  topBullets: string[],
  targetRole: string,
  companyName: string,
  roleNumber: number
): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const bullets = topBullets.length > 0
    ? topBullets.map(b => `    • ${b.replace(/^[•\-\*\u2022]\s/, '').replace(/^\d+\.\s/, '')}`).join('\n')
    : `    • Proven track record of delivering high-impact solutions at scale
    • Strong cross-functional collaboration skills and technical leadership
    • Deep expertise in distributed systems and modern development practices`

  return `${today}

Hiring Manager
${companyName}

Dear Hiring Manager,

I am writing to express my strong interest in the ${targetRole} position at ${companyName}. With a proven track record of building and scaling production systems, I am confident that my experience directly aligns with what your team needs.

Throughout my career, I have consistently delivered measurable results:

${bullets}

What excites me most about ${companyName} is the opportunity to work on challenging technical problems alongside talented engineers who value craft and impact. I thrive in environments where the bar for quality is high, and I believe my experience would allow me to contribute meaningfully from day one.

I would welcome the chance to discuss how my background can benefit your team. I am available for a conversation at your earliest convenience.

Best regards,
${name}`
}

function generateCoverLetterRTF(content: string): string {
  const paragraphs = content.split('\n')
  const rtfParagraphs = paragraphs.map(p => {
    const escaped = p
      .replace(/\\/g, '\\\\')
      .replace(/\{/g, '\\{')
      .replace(/\}/g, '\\}')
    return `{\\fs22 ${escaped}}\\par`
  }).join('\n')

  return `{\\rtf1\\ansi\\deff0
{\\fonttbl{\\f0 Georgia;}{\\f1 Calibri;}}
\\paperw12240\\paperh15840\\margins1440\\margl1440\\margr1440
${rtfParagraphs}
\\par
{\\f1\\fs16 Generated by QRSQPI Resume Intelligence}
}`
}