// -------------------------------------------------------
// /api/deliverables/linkedin - Generate LinkedIn profile text
// Returns structured LinkedIn profile optimization text
// -------------------------------------------------------

import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { resumeText, targetRole = 'Software Engineer', baseScore, panelEvaluation } = body

    if (!resumeText) {
      return NextResponse.json(
        { error: 'Resume text is required to generate LinkedIn profile' },
        { status: 400 }
      )
    }

    // Parse resume sections for LinkedIn content generation
    const lines = resumeText.split('\n').filter(l => l.trim())
    const nameLine = lines[0]?.trim() || 'Professional'
    const bulletLines = lines.filter(l => /^[•\-\*\u2022]\s/.test(l.trim()) || /^\d+\.\s/.test(l.trim()))

    // Extract skills line
    const skillsLine = lines.find(l => /^skills/i.test(l.trim()))

    // Build optimized LinkedIn content
    const headline = buildHeadline(nameLine, targetRole, baseScore)
    const about = buildAbout(nameLine, targetRole, bulletLines.slice(0, 5))
    const experience = buildExperience(lines)
    const skills = buildSkills(skillsLine, targetRole)

    const profileText = `${headline}

---ABOUT---
${about}

---EXPERIENCE---
${experience}

---SKILLS---
${skills}

---
Generated by QRSQPI Resume Intelligence | ${new Date().toISOString().split('T')[0]}`

    return NextResponse.json({
      success: true,
      linkedin: {
        headline: headline,
        about: about,
        experience: experience,
        skills: skills,
      },
      fullText: profileText,
    })
  } catch (error: any) {
    console.error('LinkedIn deliverable error:', error)
    return NextResponse.json(
      { error: 'Failed to generate LinkedIn profile' },
      { status: 500 }
    )
  }
}

function buildHeadline(name: string, role: string, score: any): string {
  const seniority = role.toLowerCase().includes('senior') || role.toLowerCase().includes('staff')
    ? 'Senior '
    : role.toLowerCase().includes('principal')
      ? 'Principal '
      : role.toLowerCase().includes('lead')
        ? 'Lead '
        : ''

  const domains = ['Distributed Systems', 'Cloud Infrastructure', 'Platform Engineering', 'Data Engineering', 'Backend Systems']
  const years = score?.categories?.find((c: any) => c.name?.toLowerCase().includes('experience'))?.score
    ? '8+ '
    : '5+ '

  return `${seniority}${role} | ${years}Years Building at Scale | ${domains[Math.floor(Math.random() * domains.length)]}`
}

function buildAbout(name: string, role: string, topBullets: string[]): string {
  const cleanBullets = topBullets.map(b => b.replace(/^[•\-\*\u2022]\s/, '').replace(/^\d+\.\s/, ''))

  const achievements = cleanBullets.length > 0
    ? `\n\n${cleanBullets.map(b => `- ${b}`).join('\n')}`
    : `\n\n- Led cross-functional teams shipping platforms at scale\n- Reduced latency and improved system reliability across production services\n- Architected solutions processing high-throughput data pipelines`

  return `${name} — ${role} passionate about building reliable, scalable systems that solve real problems.${achievements}

Looking for roles where I can combine technical depth with team leadership to drive impact at scale.`
}

function buildExperience(lines: string[]): string {
  // Extract experience-related lines
  const experienceLines: string[] = []
  let inExperience = false

  for (const line of lines) {
    const trimmed = line.trim()
    if (/^experience/i.test(trimmed)) {
      inExperience = true
      continue
    }
    if (/^(education|skills|projects|certifications)/i.test(trimmed)) {
      inExperience = false
    }
    if (inExperience && trimmed) {
      experienceLines.push(trimmed)
    }
  }

  const bullets = experienceLines.filter(l =>
    /^[•\-\*\u2022]\s/.test(l) || /^\d+\.\s/.test(l)
  ).map(b => b.replace(/^[•\-\*\u2022]\s/, '').replace(/^\d+\.\s/, ''))

  if (bullets.length > 0) {
    return bullets.slice(0, 6).join('\n')
  }

  return `- Reduced P95 latency from 1.8s to 180ms, enabling 40% user growth
- Led 8 engineers across 2 squads delivering 3 revenue-generating features
- Architected real-time analytics dashboard serving 200+ daily active users
- Cut infrastructure costs by 34% through cache optimization`
}

function buildSkills(skillsLine: string | undefined, role: string): string {
  if (skillsLine) {
    return skillsLine.replace(/^skills[:\s]*/i, '').trim()
  }

  const defaults = 'Distributed Systems | Kubernetes | AWS | Microservices | CI/CD | System Design | Real-Time Data | Technical Leadership | Go | Python | PostgreSQL | Redis'
  if (role.toLowerCase().includes('frontend')) {
    return 'React | TypeScript | Next.js | CSS Architecture | Web Performance | Design Systems | Accessibility | Testing | Node.js | GraphQL'
  }
  if (role.toLowerCase().includes('data') || role.toLowerCase().includes('ml')) {
    return 'Python | Machine Learning | Data Engineering | SQL | TensorFlow | PyTorch | Statistics | Feature Engineering | MLOps | Apache Spark'
  }
  return defaults
}